import { describe, it, expect } from 'vitest'
import { generateDockerCompose, generateClaudeMd, generateStructuredJson } from './exportService'
import type { Project } from '../store/projectStore'

const mockProject: Project = {
    id: 'test-1',
    name: 'Test Project',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    nodes: [
        { id: 'gw-1', type: 'gateway', position: { x: 0, y: 0 }, data: { label: 'My Gateway', technology: 'nginx' } },
        { id: 'svc-1', type: 'service', position: { x: 0, y: 0 }, data: { label: 'My Service', technology: 'express' } },
        { id: 'db-1', type: 'database', position: { x: 0, y: 0 }, data: { label: 'My Database', technology: 'postgresql' } }
    ],
    edges: [
        { id: 'e1', source: 'gw-1', target: 'svc-1' },
        { id: 'e2', source: 'svc-1', target: 'db-1' }
    ],
    checkpoints: []
}

describe('exportService', () => {
    it('generates valid JSON export', () => {
        const jsonStr = generateStructuredJson(mockProject)
        const parsed = JSON.parse(jsonStr)
        expect(parsed.name).toBe('Test Project')
        expect(parsed.architecture.components.length).toBe(3)
        expect(parsed.architecture.connections.length).toBe(2)
        expect(parsed.architecture.components[0].label).toBe('My Gateway')
    })

    it('generates a valid Docker Compose structure', () => {
        const docker = generateDockerCompose(mockProject.nodes, mockProject.edges)
        expect(docker).toContain('version: "3.9"')
        expect(docker).toContain('services:')
        // check slugified names
        expect(docker).toContain('my-gateway:')
        expect(docker).toContain('my-service:')
        expect(docker).toContain('my-database:')
        // check images
        expect(docker).toContain('image: nginx:alpine')
        expect(docker).toContain('image: postgres:16-alpine')
        // check dependencies
        expect(docker).toContain('depends_on:')
        expect(docker).toContain('- my-service') // gateway depends on service
        expect(docker).toContain('- my-database') // service depends on database
    })

    it('generates CLAUDE.md architecture context', () => {
        const claude = generateClaudeMd(mockProject)
        expect(claude).toContain('# Test Project')
        expect(claude).toContain('Auto-generated by **Kurguide**')
        expect(claude).toContain('### Entry Points')
        expect(claude).toContain('**My Gateway**')
        expect(claude).toContain('My Gateway → My Service')
    })
})
