import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

/**
 * PDF Export — Captures the ReactFlow canvas as an image and wraps it in a PDF.
 */
export async function exportCanvasToPDF(projectName: string): Promise<void> {
    // Use the main react-flow container instead of viewport to capture SVGs correctly
    const flowContainer = document.querySelector('.react-flow') as HTMLElement
    if (!flowContainer) {
        throw new Error('Canvas container not found')
    }

    // html-to-image often drops SVGs that have active CSS animations.
    // Inject a temporary style to freeze animations during capture.
    const style = document.createElement('style')
    style.innerHTML = `
        .react-flow__edge-path, .animate-ghost-pulse {
            animation: none !important;
            transition: none !important;
        }
    `
    document.head.appendChild(style)

    let dataUrl: string
    try {
        // Capture as PNG
        dataUrl = await toPng(flowContainer, {
            backgroundColor: '#0c0c0e',
            quality: 1,
            pixelRatio: 2,
        })
    } finally {
        // Clean up the style
        document.head.removeChild(style)
    }

    // Create PDF (landscape A4)
    const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()

    // Title
    pdf.setFontSize(16)
    pdf.setTextColor(255, 255, 255)
    pdf.setFillColor(12, 12, 14)
    pdf.rect(0, 0, pageWidth, pageHeight, 'F')
    pdf.text(projectName, 14, 14)

    // Subtitle
    pdf.setFontSize(8)
    pdf.setTextColor(150, 150, 150)
    pdf.text(`Generated by Kurguide · ${new Date().toLocaleDateString()}`, 14, 20)

    // Image
    const imgProps = pdf.getImageProperties(dataUrl)
    const imgRatio = imgProps.width / imgProps.height
    const maxWidth = pageWidth - 28
    const maxHeight = pageHeight - 32
    let imgW = maxWidth
    let imgH = imgW / imgRatio

    if (imgH > maxHeight) {
        imgH = maxHeight
        imgW = imgH * imgRatio
    }

    const x = (pageWidth - imgW) / 2
    pdf.addImage(dataUrl, 'PNG', x, 26, imgW, imgH)

    // Download
    pdf.save(`${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_architecture.pdf`)
}
